service: saasloBackend

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  timeout: 15
  memorySize: 2048

functions:
  hello:
    handler: handler.sls
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      NODE_ENV: development